// 六级核心高频词表（真题高频 + 常考核心）
// 格式：[单词, 音标, 中文释义]，音标可为 '' 简化
// 目标：约 400 词，覆盖考研英语中六级高频核心；可随时在文件里增删扩充
export const VOCAB = [
  ['abandon', '', 'v. 放弃；抛弃'],
  ['ability', '', 'n. 能力；才能'],
  ['absorb', '', 'v. 吸收；使专心'],
  ['abstract', '', 'adj. 抽象的 n. 摘要'],
  ['academic', '', 'adj. 学术的；学院的'],
  ['accelerate', '', 'v. 加速；促进'],
  ['accept', '', 'v. 接受；认可'],
  ['access', '', 'n. 通道；接近 v. 访问'],
  ['accommodate', '', 'v. 容纳；使适应'],
  ['accomplish', '', 'v. 完成；实现'],
  ['account', '', 'n. 账户；说明 v. 认为'],
  ['accumulate', '', 'v. 积累；堆积'],
  ['accurate', '', 'adj. 准确的；精确的'],
  ['achieve', '', 'v. 实现；达到'],
  ['acquire', '', 'v. 获得；学到'],
  ['adapt', '', 'v. 适应；改编'],
  ['adequate', '', 'adj. 充足的；胜任的'],
  ['adjust', '', 'v. 调整；适应'],
  ['administration', '', 'n. 管理；行政机关'],
  ['admire', '', 'v. 钦佩；欣赏'],
  ['adopt', '', 'v. 采用；收养'],
  ['advance', '', 'v. 前进；提升 n. 进展'],
  ['advantage', '', 'n. 优势；有利条件'],
  ['adverse', '', 'adj. 不利的；相反的'],
  ['advocate', '', 'v. 提倡 n. 拥护者'],
  ['affect', '', 'v. 影响；感动'],
  ['afford', '', 'v. 负担得起；提供'],
  ['agenda', '', 'n. 议程；日程表'],
  ['aggressive', '', 'adj. 好斗的；有进取心的'],
  ['alter', '', 'v. 改变；修改'],
  ['alternative', '', 'n. 选择 adj. 可替代的'],
  ['ambiguous', '', 'adj. 模糊的；含糊的'],
  ['ambition', '', 'n. 雄心；抱负'],
  ['analyze', '', 'v. 分析'],
  ['ancient', '', 'adj. 古代的；古老的'],
  ['anticipate', '', 'v. 预期；预料'],
  ['anxiety', '', 'n. 焦虑；担心'],
  ['apparent', '', 'adj. 明显的；表面上的'],
  ['appeal', '', 'v. 呼吁；吸引 n. 上诉'],
  ['applaud', '', 'v. 鼓掌；称赞'],
  ['applicable', '', 'adj. 适用的；合适的'],
  ['apply', '', 'v. 申请；应用'],
  ['appoint', '', 'v. 任命；约定'],
  ['appreciate', '', 'v. 欣赏；感激'],
  ['approach', '', 'v. 接近 n. 方法'],
  ['appropriate', '', 'adj. 适当的 v. 挪用'],
  ['approve', '', 'v. 批准；赞成'],
  ['arbitrary', '', 'adj. 任意的；专断的'],
  ['argue', '', 'v. 争论；论证'],
  ['arise', '', 'v. 出现；上升'],
  ['arrange', '', 'v. 安排；整理'],
  ['artificial', '', 'adj. 人造的；虚假的'],
  ['aspect', '', 'n. 方面；外观'],
  ['assemble', '', 'v. 集合；装配'],
  ['assert', '', 'v. 断言；主张'],
  ['assess', '', 'v. 评估；估价'],
  ['assign', '', 'v. 分配；指派'],
  ['assist', '', 'v. 帮助；协助'],
  ['associate', '', 'v. 联系 adj. 副的'],
  ['assume', '', 'v. 假定；承担'],
  ['assure', '', 'v. 保证；使确信'],
  ['attach', '', 'v. 附上；系上'],
  ['attain', '', 'v. 达到；获得'],
  ['attempt', '', 'v. 尝试 n. 企图'],
  ['attitude', '', 'n. 态度；看法'],
  ['attribute', '', 'v. 归因于 n. 属性'],
  ['authority', '', 'n. 权威；当局'],
  ['available', '', 'adj. 可获得的；有空的'],
  ['average', '', 'n. 平均数 adj. 平均的'],
  ['avoid', '', 'v. 避免；回避'],
  ['aware', '', 'adj. 意识到的；知道的'],
  ['awkward', '', 'adj. 尴尬的；笨拙的'],
  ['balance', '', 'n. 平衡 v. 使平衡'],
  ['ban', '', 'v. 禁止 n. 禁令'],
  ['barrier', '', 'n. 障碍；栅栏'],
  ['basis', '', 'n. 基础；基准'],
  ['behalf', '', 'n. 代表；利益'],
  ['behavior', '', 'n. 行为；举止'],
  ['benefit', '', 'n. 利益 v. 有益于'],
  ['bias', '', 'n. 偏见 v. 使有偏见'],
  ['boundary', '', 'n. 边界；界限'],
  ['brief', '', 'adj. 简短的 v. 简要介绍'],
  ['budget', '', 'n. 预算 v. 编预算'],
  ['burden', '', 'n. 负担 v. 使负重'],
  ['campaign', '', 'n. 运动；战役'],
  ['capable', '', 'adj. 有能力的'],
  ['capacity', '', 'n. 容量；能力'],
  ['capture', '', 'v. 捕获；夺取'],
  ['category', '', 'n. 种类；范畴'],
  ['cautious', '', 'adj. 谨慎的'],
  ['cease', '', 'v. 停止；终止'],
  ['challenge', '', 'n. 挑战 v. 向…挑战'],
  ['characteristic', '', 'adj. 典型的 n. 特征'],
  ['circumstance', '', 'n. 环境；情况'],
  ['cite', '', 'v. 引用；传讯'],
  ['civilization', '', 'n. 文明；文化'],
  ['claim', '', 'v. 声称 n. 要求'],
  ['clarify', '', 'v. 澄清；阐明'],
  ['classify', '', 'v. 分类'],
  ['collapse', '', 'v. 倒塌；崩溃'],
  ['commit', '', 'v. 犯（错）；承诺'],
  ['committee', '', 'n. 委员会'],
  ['community', '', 'n. 社区；群体'],
  ['compare', '', 'v. 比较；对比'],
  ['compel', '', 'v. 强迫；迫使'],
  ['compensate', '', 'v. 补偿；赔偿'],
  ['compete', '', 'v. 竞争'],
  ['compile', '', 'v. 汇编；编辑'],
  ['complex', '', 'adj. 复杂的 n. 综合体'],
  ['complicate', '', 'v. 使复杂化'],
  ['component', '', 'n. 组成部分'],
  ['comprehensive', '', 'adj. 全面的；综合的'],
  ['comprise', '', 'v. 包含；构成'],
  ['compromise', '', 'n. 妥协 v. 折中'],
  ['conceive', '', 'v. 构想；怀孕'],
  ['concentrate', '', 'v. 集中；专心'],
  ['concept', '', 'n. 概念；观念'],
  ['concern', '', 'v. 涉及；使担忧'],
  ['conclude', '', 'v. 得出结论；结束'],
  ['conduct', '', 'v. 进行；引导 n. 行为'],
  ['conference', '', 'n. 会议；协商'],
  ['confidence', '', 'n. 信心；信任'],
  ['confirm', '', 'v. 确认；证实'],
  ['conflict', '', 'n. 冲突 v. 抵触'],
  ['conform', '', 'v. 遵守；顺应'],
  ['confront', '', 'v. 面对；遭遇'],
  ['confuse', '', 'v. 使困惑；混淆'],
  ['consequence', '', 'n. 结果；后果'],
  ['conservative', '', 'adj. 保守的'],
  ['considerable', '', 'adj. 相当大的；重要的'],
  ['consist', '', 'v. 由…组成'],
  ['consistent', '', 'adj. 一致的；连续的'],
  ['constant', '', 'adj. 不断的；恒定的'],
  ['constitute', '', 'v. 构成；建立'],
  ['constraint', '', 'n. 约束；限制'],
  ['construct', '', 'v. 建造；构造'],
  ['consume', '', 'v. 消耗；消费'],
  ['contact', '', 'n. 接触；联系 v. 联系'],
  ['contemporary', '', 'adj. 当代的；同时代的'],
  ['content', '', 'n. 内容 adj. 满足的'],
  ['contest', '', 'n. 竞赛 v. 争夺'],
  ['context', '', 'n. 上下文；背景'],
  ['contradict', '', 'v. 反驳；与…矛盾'],
  ['contrary', '', 'adj. 相反的 n. 反面'],
  ['contrast', '', 'n. 对比 v. 形成对照'],
  ['contribute', '', 'v. 贡献；捐助'],
  ['controversy', '', 'n. 争论；争议'],
  ['convenient', '', 'adj. 方便的'],
  ['convention', '', 'n. 惯例；大会'],
  ['convert', '', 'v. 转换；皈依'],
  ['convince', '', 'v. 使确信；说服'],
  ['cooperate', '', 'v. 合作；配合'],
  ['cope', '', 'v. 应付；处理'],
  ['corporate', '', 'adj. 公司的；团体的'],
  ['correspond', '', 'v. 符合；通信'],
  ['costume', '', 'n. 服装；戏装'],
  ['counsel', '', 'n. 忠告 v. 建议'],
  ['countless', '', 'adj. 无数的'],
  ['courage', '', 'n. 勇气；胆量'],
  ['crisis', '', 'n. 危机；紧要关头'],
  ['criteria', '', 'n. (criterion的复)标准'],
  ['crucial', '', 'adj. 关键的；决定性的'],
  ['cultivate', '', 'v. 培养；耕作'],
  ['currency', '', 'n. 货币；流通'],
  ['current', '', 'adj. 当前的 n. 水流；电流'],
  ['custom', '', 'n. 风俗；习惯'],
  ['cycle', '', 'n. 循环；周期'],
  ['data', '', 'n. 数据；资料'],
  ['debate', '', 'n. 辩论 v. 争论'],
  ['decade', '', 'n. 十年'],
  ['declare', '', 'v. 宣布；声明'],
  ['decline', '', 'v. 下降；婉拒'],
  ['dedicate', '', 'v. 奉献；致力于'],
  ['defeat', '', 'v. 击败 n. 失败'],
  ['defendant', '', 'n. 被告'],
  ['defense', '', 'n. 防御；辩护'],
  ['deficit', '', 'n. 赤字；亏损'],
  ['define', '', 'v. 定义；限定'],
  ['definite', '', 'adj. 明确的；肯定的'],
  ['delay', '', 'v. 推迟 n. 耽搁'],
  ['deliberate', '', 'adj. 故意的；深思熟虑的'],
  ['delicate', '', 'adj. 精巧的；微妙的'],
  ['demonstrate', '', 'v. 证明；示范'],
  ['denote', '', 'v. 表示；意味着'],
  ['deny', '', 'v. 否认；拒绝'],
  ['depart', '', 'v. 离开；出发'],
  ['depend', '', 'v. 依靠；取决于'],
  ['depict', '', 'v. 描绘；描述'],
  ['deposit', '', 'n. 存款；押金 v. 存放'],
  ['derive', '', 'v. 得到；源于'],
  ['descend', '', 'v. 下降；下来'],
  ['describe', '', 'v. 描述；形容'],
  ['deserve', '', 'v. 应得；值得'],
  ['designate', '', 'v. 指定；指派'],
  ['desperate', '', 'adj. 绝望的；拼命的'],
  ['despite', '', 'prep. 尽管'],
  ['destiny', '', 'n. 命运'],
  ['destroy', '', 'v. 摧毁；消灭'],
  ['detect', '', 'v. 察觉；侦查'],
  ['determine', '', 'v. 决定；确定'],
  ['devote', '', 'v. 奉献；致力于'],
  ['diagnose', '', 'v. 诊断'],
  ['differ', '', 'v. 不同；相异'],
  ['digest', '', 'v. 消化；理解 n. 文摘'],
  ['diligent', '', 'adj. 勤奋的'],
  ['dimension', '', 'n. 维度；尺寸'],
  ['diminish', '', 'v. 减少；缩小'],
  ['diploma', '', 'n. 文凭；毕业证书'],
  ['direct', '', 'adj. 直接的 v. 指挥'],
  ['discipline', '', 'n. 纪律；学科'],
  ['discount', '', 'n. 折扣 v. 打折'],
  ['discourage', '', 'v. 使气馁；阻止'],
  ['discriminate', '', 'v. 歧视；区别'],
  ['dispose', '', 'v. 处理；布置'],
  ['distinct', '', 'adj. 明显的；独特的'],
  ['distinguish', '', 'v. 区分；辨别'],
  ['distribute', '', 'v. 分发；分配'],
  ['disturb', '', 'v. 打扰；扰乱'],
  ['diverse', '', 'adj. 多样的；不同的'],
  ['domestic', '', 'adj. 国内的；家庭的'],
  ['dominant', '', 'adj. 占优势的；主导的'],
  ['dominate', '', 'v. 支配；统治'],
  ['dramatic', '', 'adj. 戏剧性的；巨大的'],
  ['drift', '', 'v. 漂流 n. 趋势'],
  ['durable', '', 'adj. 耐用的；持久的'],
  ['dynamic', '', 'adj. 动态的；有活力的'],
  ['economy', '', 'n. 经济；节约'],
  ['efficient', '', 'adj. 高效的'],
  ['elaborate', '', 'adj. 精心制作的 v. 详述'],
  ['eliminate', '', 'v. 消除；淘汰'],
  ['embark', '', 'v. 着手；从事'],
  ['emerge', '', 'v. 出现；浮现'],
  ['emphasis', '', 'n. 强调；重点'],
  ['enable', '', 'v. 使能够'],
  ['encounter', '', 'v. 遭遇 n. 相遇'],
  ['endeavor', '', 'n. 努力 v. 尽力'],
  ['enhance', '', 'v. 提高；增强'],
  ['enormous', '', 'adj. 巨大的'],
  ['ensure', '', 'v. 确保；保证'],
  ['entitle', '', 'v. 使有资格；给…题名'],
  ['environment', '', 'n. 环境'],
  ['equip', '', 'v. 装备；配备'],
  ['equivalent', '', 'adj. 等价的 n. 等价物'],
  ['essence', '', 'n. 本质；精华'],
  ['establish', '', 'v. 建立；确立'],
  ['estimate', '', 'v. 估计 n. 估价'],
  ['evaluate', '', 'v. 评价；估价'],
  ['eventually', '', 'adv. 最终；终于'],
  ['evident', '', 'adj. 明显的'],
  ['evolve', '', 'v. 进化；演变'],
  ['exceed', '', 'v. 超过；超出'],
  ['exception', '', 'n. 例外'],
  ['exclude', '', 'v. 排除；排斥'],
  ['execute', '', 'v. 执行；实施'],
  ['exert', '', 'v. 施加；运用'],
  ['exhaust', '', 'v. 使精疲力尽；耗尽'],
  ['exhibit', '', 'v. 展示；陈列'],
  ['expand', '', 'v. 扩大；膨胀'],
  ['expense', '', 'n. 花费；代价'],
  ['experiment', '', 'n. 实验 v. 做实验'],
  ['explicit', '', 'adj. 明确的；清楚的'],
  ['exploit', '', 'v. 开发；利用；剥削'],
  ['expose', '', 'v. 暴露；揭露'],
  ['extend', '', 'v. 延伸；扩展'],
  ['extent', '', 'n. 程度；范围'],
  ['external', '', 'adj. 外部的；外在的'],
  ['extinct', '', 'adj. 灭绝的；绝迹的'],
  ['facilitate', '', 'v. 促进；使便利'],
  ['factor', '', 'n. 因素；要素'],
  ['familiar', '', 'adj. 熟悉的'],
  ['fascinate', '', 'v. 使着迷'],
  ['fatal', '', 'adj. 致命的'],
  ['fatigue', '', 'n. 疲劳 v. 使疲劳'],
  ['feature', '', 'n. 特征；特色'],
  ['federal', '', 'adj. 联邦的'],
  ['feedback', '', 'n. 反馈'],
  ['figure', '', 'n. 数字；人物 v. 认为'],
  ['finance', '', 'n. 财政；金融'],
  ['flexible', '', 'adj. 灵活的；柔韧的'],
  ['fluctuate', '', 'v. 波动；起伏'],
  ['focus', '', 'v. 集中 n. 焦点'],
  ['forecast', '', 'v. 预测；预报'],
  ['formal', '', 'adj. 正式的'],
  ['former', '', 'adj. 以前的 n. 前者'],
  ['foster', '', 'v. 培养；促进'],
  ['foundation', '', 'n. 基础；基金会'],
  ['framework', '', 'n. 框架；结构'],
  ['frequency', '', 'n. 频率；频繁'],
  ['frustrate', '', 'v. 使沮丧；挫败'],
  ['fulfill', '', 'v. 履行；实现'],
  ['function', '', 'n. 功能 v. 运转'],
  ['fundamental', '', 'adj. 基本的 n. 基本原则'],
  ['furnish', '', 'v. 供应；陈设'],
  ['generate', '', 'v. 产生；生成'],
  ['genuine', '', 'adj. 真正的；真诚的'],
  ['globe', '', 'n. 地球；球体'],
  ['gradual', '', 'adj. 逐渐的'],
  ['grant', '', 'v. 授予 n. 拨款'],
  ['grasp', '', 'v. 抓住；理解'],
  ['gross', '', 'adj. 总体的；毛的'],
  ['guarantee', '', 'v. 保证 n. 保证书'],
  ['guideline', '', 'n. 指导方针'],
  ['handle', '', 'v. 处理 n. 手柄'],
  ['harmony', '', 'n. 和谐；融洽'],
  ['hazard', '', 'n. 危险 v. 冒险'],
  ['hesitate', '', 'v. 犹豫；踌躇'],
  ['highlight', '', 'v. 强调 n. 亮点'],
  ['hinder', '', 'v. 阻碍；妨碍'],
  ['horizon', '', 'n. 地平线；眼界'],
  ['hypothesis', '', 'n. 假设；假说'],
  ['identical', '', 'adj. 相同的'],
  ['identify', '', 'v. 识别；确定'],
  ['ignore', '', 'v. 忽视；不理会'],
  ['illustrate', '', 'v. 说明；阐明'],
  ['imitate', '', 'v. 模仿'],
  ['immense', '', 'adj. 巨大的'],
  ['impact', '', 'n. 影响；冲击 v. 影响'],
  ['implement', '', 'v. 实施 n. 工具'],
  ['imply', '', 'v. 暗示；意味'],
  ['impose', '', 'v. 强加；征收'],
  ['impress', '', 'v. 给…留下印象'],
  ['incentive', '', 'n. 刺激；激励'],
  ['incident', '', 'n. 事件；事变'],
  ['include', '', 'v. 包括；包含'],
  ['incline', '', 'v. 倾向于 n. 斜坡'],
  ['income', '', 'n. 收入'],
  ['increasingly', '', 'adv. 日益；越来越多地'],
  ['indicate', '', 'v. 表明；指示'],
  ['individual', '', 'adj. 个人的 n. 个人'],
  ['induce', '', 'v. 诱导；引起'],
  ['inevitable', '', 'adj. 不可避免的'],
  ['infect', '', 'v. 感染；传染'],
  ['infer', '', 'v. 推断；推论'],
  ['inferior', '', 'adj. 劣等的；下级的'],
  ['influence', '', 'n. 影响 v. 影响'],
  ['ingredient', '', 'n. 成分；原料'],
  ['inhabit', '', 'v. 居住于'],
  ['inherent', '', 'adj. 内在的；固有的'],
  ['inherit', '', 'v. 继承'],
  ['initial', '', 'adj. 最初的 n. 首字母'],
  ['initiate', '', 'v. 开始；发起'],
  ['inject', '', 'v. 注射；注入'],
  ['innovation', '', 'n. 创新；革新'],
  ['insight', '', 'n. 洞察力；见解'],
  ['inspect', '', 'v. 检查；视察'],
  ['inspire', '', 'v. 激励；启发'],
  ['install', '', 'v. 安装；就任'],
  ['instance', '', 'n. 例子；实例'],
  ['instant', '', 'adj. 立即的 n. 瞬间'],
  ['instinct', '', 'n. 本能；直觉'],
  ['institute', '', 'n. 机构 v. 建立'],
  ['instruct', '', 'v. 指示；教导'],
  ['integrate', '', 'v. 整合；使成一体'],
  ['intense', '', 'adj. 强烈的；紧张的'],
  ['intent', '', 'n. 意图 adj. 专心的'],
  ['interact', '', 'v. 相互作用；互动'],
  ['interfere', '', 'v. 干涉；妨碍'],
  ['internal', '', 'adj. 内部的'],
  ['interpret', '', 'v. 解释；翻译'],
  ['interrupt', '', 'v. 打断；中断'],
  ['interval', '', 'n. 间隔；间隙'],
  ['intervene', '', 'v. 干预；介入'],
  ['intimate', '', 'adj. 亲密的'],
  ['investigate', '', 'v. 调查；研究'],
  ['invest', '', 'v. 投资'],
  ['involve', '', 'v. 涉及；使参与'],
  ['isolate', '', 'v. 隔离；孤立'],
  ['issue', '', 'n. 问题；发行 v. 发布'],
  ['justify', '', 'v. 证明…正当'],
  ['keen', '', 'adj. 敏锐的；热衷的'],
  ['label', '', 'n. 标签 v. 贴标签'],
  ['labor', '', 'n. 劳动；劳工'],
  ['launch', '', 'v. 发射；发起'],
  ['lean', '', 'v. 倾斜；依靠'],
  ['legal', '', 'adj. 合法的'],
  ['legislation', '', 'n. 立法；法规'],
  ['liberal', '', 'adj. 自由的；开明的'],
  ['likely', '', 'adj. 可能的'],
  ['limit', '', 'n. 限制 v. 限定'],
  ['literally', '', 'adv. 照字面地；确实地'],
  ['maintain', '', 'v. 维持；保养'],
  ['majority', '', 'n. 多数'],
  ['manifest', '', 'adj. 明显的 v. 显示'],
  ['manipulate', '', 'v. 操纵；控制'],
  ['margin', '', 'n. 边缘；利润'],
  ['mature', '', 'adj. 成熟的 v. 使成熟'],
  ['mechanism', '', 'n. 机制；机械'],
  ['mediate', '', 'v. 调解；斡旋'],
  ['memorize', '', 'v. 记住；熟记'],
  ['migrate', '', 'v. 迁移；移居'],
  ['minimize', '', 'v. 使最小化'],
  ['minority', '', 'n. 少数；少数民族'],
  ['modest', '', 'adj. 谦虚的；适度的'],
  ['modify', '', 'v. 修改；修饰'],
  ['monitor', '', 'v. 监控 n. 监视器'],
  ['motivate', '', 'v. 激励；激发'],
  ['mutual', '', 'adj. 相互的；共同的'],
  ['neglect', '', 'v. 忽视 n. 疏忽'],
  ['negotiate', '', 'v. 谈判；协商'],
  ['neutral', '', 'adj. 中立的'],
  ['nevertheless', '', 'adv. 然而；不过'],
  ['nominate', '', 'v. 提名；任命'],
  ['normal', '', 'adj. 正常的'],
  ['notion', '', 'n. 概念；观念'],
  ['numerous', '', 'adj. 众多的'],
  ['objective', '', 'adj. 客观的 n. 目标'],
  ['oblige', '', 'v. 迫使；感激'],
  ['observe', '', 'v. 观察；遵守'],
  ['obtain', '', 'v. 获得'],
  ['obvious', '', 'adj. 明显的'],
  ['occasion', '', 'n. 场合；时机'],
  ['occupy', '', 'v. 占据；使忙碌'],
  ['occur', '', 'v. 发生；出现'],
  ['optimistic', '', 'adj. 乐观的'],
  ['option', '', 'n. 选择；选项'],
  ['orient', '', 'v. 使适应；确定方向'],
  ['original', '', 'adj. 原始的；独创的'],
  ['overall', '', 'adj. 总的 adv. 总体上'],
  ['pace', '', 'n. 步伐；节奏'],
  ['participate', '', 'v. 参与'],
  ['peculiar', '', 'adj. 奇怪的；特有的'],
  ['perceive', '', 'v. 察觉；理解'],
  ['perform', '', 'v. 执行；表演'],
  ['permanent', '', 'adj. 永久的'],
  ['persist', '', 'v. 坚持；持续'],
  ['perspective', '', 'n. 视角；观点'],
  ['phenomenon', '', 'n. 现象'],
  ['policy', '', 'n. 政策；方针'],
  ['portion', '', 'n. 部分；一份'],
  ['possess', '', 'v. 拥有；具有'],
  ['precaution', '', 'n. 预防；警惕'],
  ['precede', '', 'v. 先于；领先'],
  ['precise', '', 'adj. 精确的'],
  ['predict', '', 'v. 预测'],
  ['predominant', '', 'adj. 主要的；占优势的'],
  ['prefer', '', 'v. 更喜欢'],
  ['preliminary', '', 'adj. 初步的'],
  ['premise', '', 'n. 前提'],
  ['premium', '', 'n. 保险费；额外费用'],
  ['prescribe', '', 'v. 开处方；规定'],
  ['preserve', '', 'v. 保护；保存'],
  ['prevail', '', 'v. 流行；占优势'],
  ['previous', '', 'adj. 先前的'],
  ['primary', '', 'adj. 主要的；初级的'],
  ['principle', '', 'n. 原则；原理'],
  ['priority', '', 'n. 优先（权）'],
  ['procedure', '', 'n. 程序；步骤'],
  ['proceed', '', 'v. 继续进行'],
  ['process', '', 'n. 过程 v. 处理'],
  ['proclaim', '', 'v. 宣布；声明'],
  ['produce', '', 'v. 生产 n. 农产品'],
  ['professional', '', 'adj. 专业的 n. 专业人士'],
  ['profound', '', 'adj. 深刻的；深远的'],
  ['program', '', 'n. 节目；程序；计划'],
  ['prohibit', '', 'v. 禁止；阻止'],
  ['prominent', '', 'adj. 突出的；著名的'],
  ['promote', '', 'v. 促进；晋升'],
  ['prompt', '', 'adj. 迅速的 v. 促使'],
  ['proportion', '', 'n. 比例；部分'],
  ['proposal', '', 'n. 提议；方案'],
  ['prospect', '', 'n. 前景；展望'],
  ['protect', '', 'v. 保护'],
  ['protest', '', 'v. 抗议 n. 抗议'],
  ['provide', '', 'v. 提供'],
  ['provoke', '', 'v. 激起；挑拨'],
  ['purchase', '', 'v. 购买 n. 购买'],
  ['pursue', '', 'v. 追求；从事'],
  ['qualify', '', 'v. 使合格；取得资格'],
  ['quantity', '', 'n. 数量'],
  ['radical', '', 'adj. 激进的；根本的'],
  ['random', '', 'adj. 随机的'],
  ['range', '', 'n. 范围；一系列'],
  ['rarely', '', 'adv. 很少；难得'],
  ['rate', '', 'n. 比率；速度 v. 评级'],
  ['rational', '', 'adj. 理性的；合理的'],
  ['react', '', 'v. 反应'],
  ['realistic', '', 'adj. 现实的'],
  ['reasonable', '', 'adj. 合理的'],
  ['recall', '', 'v. 回忆；召回'],
  ['receive', '', 'v. 收到；接待'],
  ['recognize', '', 'v. 认出；承认'],
  ['recommend', '', 'v. 推荐；建议'],
  ['recover', '', 'v. 恢复；康复'],
  ['reflect', '', 'v. 反映；思考'],
  ['reform', '', 'n. 改革 v. 改革'],
  ['regard', '', 'v. 看待 n. 尊重'],
  ['regulate', '', 'v. 管理；调节'],
  ['reinforce', '', 'v. 加强；强化'],
  ['reject', '', 'v. 拒绝；排斥'],
  ['relevant', '', 'adj. 相关的'],
  ['relieve', '', 'v. 减轻；缓解'],
  ['reluctant', '', 'adj. 不情愿的'],
  ['rely', '', 'v. 依赖；依靠'],
  ['remark', '', 'v. 评论 n. 言论'],
  ['remedy', '', 'n. 补救；疗法'],
  ['remote', '', 'adj. 遥远的；偏僻的'],
  ['remove', '', 'v. 移除；去掉'],
  ['render', '', 'v. 使成为；提供'],
  ['renew', '', 'v. 更新；续借'],
  ['replace', '', 'v. 替代'],
  ['represent', '', 'v. 代表；体现'],
  ['require', '', 'v. 需要；要求'],
  ['resemble', '', 'v. 像；类似'],
  ['reserve', '', 'v. 保留 n. 储备'],
  ['resolve', '', 'v. 解决；决心'],
  ['resource', '', 'n. 资源'],
  ['respect', '', 'v. 尊敬 n. 方面'],
  ['respond', '', 'v. 回应；反应'],
  ['restore', '', 'v. 恢复；修复'],
  ['restrict', '', 'v. 限制；约束'],
  ['retain', '', 'v. 保持；保留'],
  ['reveal', '', 'v. 揭示；透露'],
  ['revenge', '', 'n. 报复 v. 复仇'],
  ['reverse', '', 'v. 颠倒 n. 相反 adj. 反向的'],
  ['revise', '', 'v. 修订；复习'],
  ['reward', '', 'n. 报酬 v. 奖赏'],
  ['risk', '', 'n. 风险 v. 冒险'],
  ['routine', '', 'n. 常规 adj. 例行的'],
  ['sacrifice', '', 'v. 牺牲 n. 献祭'],
  ['satisfy', '', 'v. 满足；使满意'],
  ['scale', '', 'n. 规模；刻度 v. 攀登'],
  ['scan', '', 'v. 扫描；浏览'],
  ['scenario', '', 'n. 情景；方案'],
  ['schedule', '', 'n. 时间表 v. 安排'],
  ['scope', '', 'n. 范围；余地'],
  ['section', '', 'n. 部分；章节'],
  ['secure', '', 'adj. 安全的 v. 获得'],
  ['seek', '', 'v. 寻求；追求'],
  ['seize', '', 'v. 抓住；夺取'],
  ['sensitive', '', 'adj. 敏感的'],
  ['sequence', '', 'n. 序列；顺序'],
  ['significant', '', 'adj. 重要的；显著的'],
  ['similar', '', 'adj. 相似的'],
  ['simulate', '', 'v. 模拟；假装'],
  ['simultaneous', '', 'adj. 同时的'],
  ['situation', '', 'n. 形势；处境'],
  ['sketch', '', 'n. 草图 v. 素描'],
  ['so-called', '', 'adj. 所谓的'],
  ['sole', '', 'adj. 唯一的 n. 鞋底'],
  ['sophisticated', '', 'adj. 复杂的；老练的'],
  ['source', '', 'n. 来源；源头'],
  ['specific', '', 'adj. 具体的；特定的'],
  ['specify', '', 'v. 指定；详细说明'],
  ['spectrum', '', 'n. 光谱；范围'],
  ['speculate', '', 'v. 推测；投机'],
  ['sponsor', '', 'v. 赞助 n. 赞助人'],
  ['stable', '', 'adj. 稳定的'],
  ['standard', '', 'n. 标准 adj. 标准的'],
  ['standpoint', '', 'n. 立场；观点'],
  ['statistical', '', 'adj. 统计的'],
  ['status', '', 'n. 地位；身份'],
  ['stimulate', '', 'v. 刺激；激励'],
  ['strategy', '', 'n. 战略；策略'],
  ['stress', '', 'n. 压力 v. 强调'],
  ['structure', '', 'n. 结构 v. 构建'],
  ['submit', '', 'v. 提交；屈服'],
  ['subsequent', '', 'adj. 随后的'],
  ['substance', '', 'n. 物质；实质'],
  ['substantial', '', 'adj. 大量的；实质的'],
  ['substitute', '', 'n. 代替物 v. 代替'],
  ['subtle', '', 'adj. 微妙的；敏锐的'],
  ['sufficient', '', 'adj. 足够的'],
  ['summarize', '', 'v. 总结'],
  ['superior', '', 'adj. 优越的 n. 上级'],
  ['supplement', '', 'v. 补充 n. 附录'],
  ['supply', '', 'v. 供应 n. 供给'],
  ['suppose', '', 'v. 假定；猜想'],
  ['surpass', '', 'v. 超过；优于'],
  ['surplus', '', 'n. 剩余 adj. 过剩的'],
  ['survive', '', 'v. 幸存；存活'],
  ['suspend', '', 'v. 暂停；悬挂'],
  ['sustain', '', 'v. 维持；支撑'],
  ['symbol', '', 'n. 符号；象征'],
  ['sympathy', '', 'n. 同情；同感'],
  ['tackle', '', 'v. 处理；对付'],
  ['temporary', '', 'adj. 临时的'],
  ['tendency', '', 'n. 倾向；趋势'],
  ['terminate', '', 'v. 终止；结束'],
  ['theory', '', 'n. 理论'],
  ['therefore', '', 'adv. 因此'],
  ['threaten', '', 'v. 威胁'],
  ['tolerate', '', 'v. 容忍；忍受'],
  ['trace', '', 'v. 追踪 n. 痕迹'],
  ['transfer', '', 'v. 转移；转账'],
  ['transform', '', 'v. 转变；改造'],
  ['transition', '', 'n. 过渡；转变'],
  ['transmit', '', 'v. 传输；传播'],
  ['transport', '', 'v. 运输 n. 交通'],
  ['trend', '', 'n. 趋势'],
  ['trigger', '', 'v. 引发 n. 扳机'],
  ['ultimate', '', 'adj. 最终的；根本的'],
  ['undergo', '', 'v. 经历；遭受'],
  ['undertake', '', 'v. 承担；着手'],
  ['uniform', '', 'n. 制服 adj. 统一的'],
  ['unique', '', 'adj. 独特的'],
  ['universal', '', 'adj. 普遍的'],
  ['update', '', 'v. 更新 n. 更新'],
  ['urban', '', 'adj. 城市的'],
  ['urge', '', 'v. 敦促；催促'],
  ['urgent', '', 'adj. 紧急的'],
  ['utilize', '', 'v. 利用'],
  ['valid', '', 'adj. 有效的；正当的'],
  ['vanish', '', 'v. 消失'],
  ['variable', '', 'adj. 可变的 n. 变量'],
  ['variety', '', 'n. 多样；种类'],
  ['venture', '', 'n. 风险项目 v. 冒险'],
  ['verify', '', 'v. 核实；证明'],
  ['versatile', '', 'adj. 多才多艺的'],
  ['version', '', 'n. 版本'],
  ['via', '', 'prep. 经由；通过'],
  ['victim', '', 'n. 受害者'],
  ['view', '', 'n. 观点；视野 v. 看待'],
  ['violate', '', 'v. 违反；侵犯'],
  ['virtual', '', 'adj. 虚拟的；实际上的'],
  ['visible', '', 'adj. 可见的'],
  ['vision', '', 'n. 视力；愿景'],
  ['vital', '', 'adj. 至关重要的'],
  ['vivid', '', 'adj. 生动的'],
  ['vulnerable', '', 'adj. 易受伤害的'],
  ['welfare', '', 'n. 福利'],
  ['whereas', '', 'conj. 而；然而'],
  ['withdraw', '', 'v. 撤回；取款'],
  ['withstand', '', 'v. 经受住；承受'],
  ['witness', '', 'n. 目击者 v. 目击'],
  ['worthwhile', '', 'adj. 值得的'],
  ['yield', '', 'v. 产生；屈服 n. 产量'],
]

// 单词去重保护
export const VOCAB_MAP = new Map()
for (const [w] of VOCAB) {
  if (!VOCAB_MAP.has(w)) VOCAB_MAP.set(w, true)
}
export const VOCAB_SIZE = VOCAB.length