// 六级扩充词表 A（常考基础 + 高频动词/名词）
export const EXTRA = [
  ['abolish', 'v. 废除；取消'],
  ['abrupt', 'adj. 突然的；唐突的'],
  ['absurd', 'adj. 荒谬的'],
  ['abundant', 'adj. 丰富的；充裕的'],
  ['accent', 'n. 口音；重音'],
  ['acceptance', 'n. 接受；赞同'],
  ['accessible', 'adj. 可接近的；易得到的'],
  ['accident', 'n. 事故；意外'],
  ['accompany', 'v. 陪伴；伴随'],
  ['accord', 'n. 一致 v. 给予'],
  ['accordingly', 'adv. 因此；相应地'],
  ['accountant', 'n. 会计师'],
  ['accumulation', 'n. 积累'],
  ['accuracy', 'n. 准确性'],
  ['accuse', 'v. 指控；指责'],
  ['accustomed', 'adj. 习惯的'],
  ['ache', 'n. 疼痛 v. 疼'],
  ['acid', 'n. 酸 adj. 酸的'],
  ['acknowledge', 'v. 承认；致谢'],
  ['acquaint', 'v. 使熟悉'],
  ['acute', 'adj. 急性的；敏锐的'],
  ['addition', 'n. 增加；加法'],
  ['address', 'n. 地址 v. 处理；演讲'],
  ['adequate', 'adj. 足够的'],
  ['adhere', 'v. 坚持；粘附'],
  ['adjacent', 'adj. 邻近的'],
  ['adjoin', 'v. 毗连'],
  ['administer', 'v. 管理；执行'],
  ['admiration', 'n. 钦佩'],
  ['admission', 'n. 准许进入；承认'],
  ['adolescent', 'n. 青少年 adj. 青春期的'],
  ['adopt', 'v. 采用'],
  ['adore', 'v. 崇拜；喜爱'],
  ['advancement', 'n. 进步'],
  ['adventure', 'n. 冒险'],
  ['advertise', 'v. 做广告'],
  ['aerial', 'adj. 空中的'],
  ['aeroplane', 'n. 飞机'],
  ['aesthetic', 'adj. 审美的'],
  ['affection', 'n. 喜爱；感情'],
  ['affiliate', 'v. 使隶属 n. 附属机构'],
  ['affirm', 'v. 断言；确认'],
  ['agony', 'n. 极度痛苦'],
  ['agreeable', 'adj. 令人愉快的'],
  ['agriculture', 'n. 农业'],
  ['aircraft', 'n. 飞机；航空器'],
  ['airline', 'n. 航空公司'],
  ['airport', 'n. 机场'],
  ['alarm', 'n. 警报 v. 使惊恐'],
  ['alert', 'adj. 警觉的 v. 提醒'],
  ['alien', 'adj. 外国的 n. 外星人'],
  ['alike', 'adj. 相似的 adv. 一样地'],
  ['allocate', 'v. 分配；拨给'],
  ['allowance', 'n. 津贴；允许'],
  ['ally', 'n. 同盟国 v. 结盟'],
  ['alongside', 'prep. 在…旁边'],
  ['alphabet', 'n. 字母表'],
  ['alteration', 'n. 改动'],
  ['altitude', 'n. 海拔；高度'],
  ['amateur', 'n. 业余爱好者 adj. 业余的'],
  ['amaze', 'v. 使惊奇'],
  ['ambassador', 'n. 大使'],
  ['ambiguous', 'adj. 含糊不清的'],
  ['ambulance', 'n. 救护车'],
  ['amid', 'prep. 在…之中'],
  ['amount', 'n. 数量 v. 总计'],
  ['ample', 'adj. 充足的'],
  ['amplify', 'v. 放大；增强'],
  ['amuse', 'v. 逗乐'],
  ['analogy', 'n. 类比'],
  ['analytic', 'adj. 分析的'],
  ['ancestor', 'n. 祖先'],
  ['anchor', 'n. 锚 v. 抛锚'],
  ['angle', 'n. 角度'],
  ['animate', 'v. 使有生气 adj. 有生命的'],
  ['anniversary', 'n. 周年纪念日'],
  ['announce', 'v. 宣布'],
  ['annual', 'adj. 每年的 n. 年刊'],
  ['anonymous', 'adj. 匿名的'],
  ['apartment', 'n. 公寓'],
  ['apologize', 'v. 道歉'],
  ['apparatus', 'n. 器械；仪器'],
  ['appearance', 'n. 出现；外貌'],
  ['appendix', 'n. 附录；阑尾'],
  ['appetite', 'n. 食欲；欲望'],
  ['appliance', 'n. 器具；器械'],
  ['applicant', 'n. 申请人'],
  ['appointment', 'n. 约会；任命'],
  ['appraisal', 'n. 评价；估价'],
  ['appreciable', 'adj. 可感知的'],
  ['apprehension', 'n. 忧虑；理解'],
  ['approval', 'n. 批准；赞成'],
  ['approximately', 'adv. 大约'],
  ['apt', 'adj. 易于…的；恰当的'],
  ['arab', 'adj. 阿拉伯的'],
  ['architect', 'n. 建筑师'],
  ['architecture', 'n. 建筑学'],
  ['arena', 'n. 竞技场；舞台'],
  ['argument', 'n. 争论；论据'],
  ['arithmetic', 'n. 算术'],
  ['array', 'n. 一系列；陈列'],
  ['arrogant', 'adj. 傲慢的'],
  ['artery', 'n. 动脉；干线'],
  ['article', 'n. 文章；物品'],
  ['artistic', 'adj. 艺术的'],
  ['ascend', 'v. 上升'],
  ['ascertain', 'v. 查明'],
  ['ashamed', 'adj. 羞愧的'],
  ['aside', 'adv. 在旁边'],
  ['assault', 'n. 攻击 v. 袭击'],
  ['assessment', 'n. 评估'],
  ['asset', 'n. 资产；优点'],
  ['assignment', 'n. 任务；作业'],
  ['assistance', 'n. 帮助'],
  ['associate', 'v. 联系'],
  ['association', 'n. 协会；联想'],
  ['assumption', 'n. 假设'],
  ['astonish', 'v. 使惊讶'],
  ['astronaut', 'n. 宇航员'],
  ['astronomy', 'n. 天文学'],
  ['athlete', 'n. 运动员'],
  ['atlas', 'n. 地图集'],
  ['atmosphere', 'n. 大气层；气氛'],
  ['atom', 'n. 原子'],
  ['attendance', 'n. 出席；出席人数'],
  ['attendant', 'n. 服务员'],
  ['attention', 'n. 注意'],
  ['attorney', 'n. 律师'],
  ['attraction', 'n. 吸引力；景点'],
  ['audible', 'adj. 听得见的'],
  ['audience', 'n. 观众'],
  ['audio', 'adj. 音频的'],
  ['audit', 'v. 审计'],
  ['automate', 'v. 使自动化'],
  ['automatic', 'adj. 自动的'],
  ['autonomous', 'adj. 自治的'],
  ['auxiliary', 'adj. 辅助的'],
  ['available', 'adj. 可获得的'],
  ['aviation', 'n. 航空'],
  ['award', 'n. 奖品 v. 授予'],
  ['axis', 'n. 轴'],
  ['bacterium', 'n. 细菌'],
  ['balloon', 'n. 气球'],
  ['bankrupt', 'adj. 破产的'],
  ['banner', 'n. 横幅'],
  ['barely', 'adv. 仅仅；几乎不'],
  ['bargain', 'n. 便宜货 v. 讨价还价'],
  ['barrel', 'n. 桶'],
  ['bathe', 'v. 洗澡；浸'],
  ['battery', 'n. 电池'],
  ['beach', 'n. 海滩'],
  ['beam', 'n. 光束；横梁'],
  ['bearing', 'n. 轴承；关系'],
  ['beloved', 'adj. 心爱的'],
  ['betray', 'v. 背叛；泄露'],
  ['beverage', 'n. 饮料'],
  ['bible', 'n. 圣经'],
  ['bibliography', 'n. 参考书目'],
  ['bid', 'v. 出价 n. 投标'],
  ['bind', 'v. 捆绑；约束'],
  ['biography', 'n. 传记'],
  ['biology', 'n. 生物学'],
  ['bitter', 'adj. 苦的；激烈的'],
  ['blast', 'n. 爆炸 v. 爆破'],
  ['blaze', 'n. 火焰 v. 燃烧'],
  ['bleed', 'v. 流血'],
  ['blend', 'v. 混合 n. 混合物'],
  ['bless', 'v. 祝福'],
  ['bloom', 'n. 花 v. 开花'],
  ['blossom', 'n. 花朵 v. 开花'],
  ['blur', 'v. 使模糊 n. 模糊'],
  ['blush', 'v. 脸红'],
  ['boast', 'v. 自夸 n. 夸口'],
  ['bold', 'adj. 大胆的；粗体的'],
  ['bond', 'n. 债券；纽带'],
  ['boost', 'v. 促进 n. 推动'],
  ['bother', 'v. 打扰'],
  ['bounce', 'v. 弹起 n. 弹跳'],
  ['bound', 'adj. 必然的；被束缚的'],
  ['bow', 'n. 弓；鞠躬 v. 鞠躬'],
  ['brand', 'n. 品牌；烙印'],
  ['bravery', 'n. 勇敢'],
  ['breed', 'v. 繁殖 n. 品种'],
  ['breeze', 'n. 微风'],
  ['bribe', 'v. 贿赂 n. 贿赂'],
  ['brilliant', 'adj. 杰出的；明亮的'],
  ['broaden', 'v. 加宽'],
  ['broken', 'adj. 破碎的'],
  ['browse', 'v. 浏览'],
  ['brutal', 'adj. 残暴的'],
  ['bubble', 'n. 气泡 v. 冒泡'],
  ['bud', 'n. 芽 v. 发芽'],
  ['bulk', 'n. 大批；体积'],
  ['bullet', 'n. 子弹'],
  ['bulletin', 'n. 公告'],
  ['bump', 'v. 碰撞 n. 肿块'],
  ['bunch', 'n. 束；串'],
  ['bureau', 'n. 局；办事处'],
  ['burst', 'v. 爆裂 n. 爆炸'],
  ['bury', 'v. 埋葬'],
  ['butterfly', 'n. 蝴蝶'],
  ['cabinet', 'n. 内阁；橱柜'],
  ['cable', 'n. 电缆；缆绳'],
  ['calculate', 'v. 计算'],
  ['calculator', 'n. 计算器'],
  ['calendar', 'n. 日历'],
  ['calm', 'adj. 平静的 v. 使平静'],
  ['candidate', 'n. 候选人'],
  ['candy', 'n. 糖果'],
  ['capable', 'adj. 有能力的'],
  ['capital', 'n. 首都；资本'],
  ['captain', 'n. 船长；队长'],
  ['captive', 'n. 俘虏 adj. 被俘的'],
  ['carbon', 'n. 碳'],
  ['cargo', 'n. 货物'],
  ['carpenter', 'n. 木匠'],
  ['carriage', 'n. 马车；车厢'],
  ['carrier', 'n. 运送者；载体'],
  ['cartoon', 'n. 卡通；漫画'],
  ['cashier', 'n. 出纳员'],
  ['cassette', 'n. 磁带'],
  ['cast', 'v. 投；抛 n. 演员表'],
  ['casual', 'adj. 随便的；偶然的'],
  ['casualty', 'n. 伤亡者'],
  ['catalog', 'n. 目录'],
  ['cataloguer', 'n. 编目者'],
  ['catastrophe', 'n. 大灾难'],
  ['cement', 'n. 水泥 v. 巩固'],
  ['center', 'n. 中心'],
  ['ceremony', 'n. 典礼；仪式'],
  ['certificate', 'n. 证书'],
  ['chain', 'n. 链子 v. 用链拴住'],
  ['chairman', 'n. 主席'],
  ['chamber', 'n. 房间；议院'],
  ['champion', 'n. 冠军'],
  ['channel', 'n. 频道；渠道'],
  ['chapter', 'n. 章节'],
  ['character', 'n. 性格；角色'],
  ['charm', 'n. 魅力 v. 迷住'],
  ['chart', 'n. 图表'],
  ['charter', 'n. 宪章 v. 包租'],
  ['chase', 'v. 追逐 n. 追赶'],
  ['cherish', 'v. 珍爱'],
  ['chew', 'v. 咀嚼'],
  ['chief', 'adj. 主要的 n. 首领'],
  ['chill', 'n. 寒冷 v. 使寒冷'],
  ['choke', 'v. 窒息；堵塞'],
  ['chop', 'v. 砍 n. 排骨'],
  ['Christian', 'n. 基督徒'],
  ['chronic', 'adj. 慢性的'],
  ['circuit', 'n. 电路；环行'],
  ['circular', 'adj. 圆形的；循环的'],
  ['circulate', 'v. 流通；循环'],
  ['cite', 'v. 引用'],
  ['civil', 'adj. 公民的；民事的'],
  ['clap', 'v. 拍手'],
  ['clarify', 'v. 澄清'],
  ['clash', 'n. 冲突 v. 冲突'],
  ['classification', 'n. 分类'],
  ['clause', 'n. 条款；从句'],
  ['claw', 'n. 爪'],
  ['clay', 'n. 黏土'],
  ['clergy', 'n. 神职人员'],
  ['cliff', 'n. 悬崖'],
  ['climate', 'n. 气候'],
  ['cling', 'v. 紧紧抓住'],
  ['clinic', 'n. 诊所'],
  ['clip', 'n. 夹子 v. 剪短'],
  ['clockwise', 'adj. 顺时针的'],
  ['clone', 'n. 克隆 v. 克隆'],
  ['closet', 'n. 壁橱'],
  ['cluster', 'n. 簇 v. 群集'],
  ['clutch', 'v. 抓住 n. 离合器'],
  ['coach', 'n. 教练；长途汽车'],
  ['coalition', 'n. 联盟'],
  ['coast', 'n. 海岸'],
  ['cocaine', 'n. 可卡因'],
  ['code', 'n. 代码；法典'],
  ['cognitive', 'adj. 认知的'],
  ['coherent', 'adj. 连贯的'],
  ['coincide', 'v. 同时发生；一致'],
  ['collaborate', 'v. 合作'],
  ['colleague', 'n. 同事'],
  ['collective', 'adj. 集体的 n. 集体'],
  ['collision', 'n. 碰撞'],
  ['colony', 'n. 殖民地'],
  ['column', 'n. 柱；专栏'],
  ['combat', 'v. 战斗 n. 搏斗'],
  ['combine', 'v. 联合'],
  ['comfort', 'n. 安慰 v. 安慰'],
  ['command', 'v. 命令 n. 指挥'],
  ['commemorate', 'v. 纪念'],
  ['commence', 'v. 开始'],
  ['comment', 'n. 评论 v. 评论'],
  ['commerce', 'n. 商业'],
  ['commission', 'n. 委员会；佣金'],
  ['commodity', 'n. 商品'],
  ['commonsense', 'n. 常识'],
  ['communicate', 'v. 交流'],
  ['communist', 'n. 共产主义者'],
  ['companion', 'n. 同伴'],
  ['comparable', 'adj. 可比较的'],
  ['comparison', 'n. 比较'],
  ['compartment', 'n. 隔间'],
  ['compassion', 'n. 同情'],
  ['compatible', 'adj. 兼容的'],
  ['compensation', 'n. 补偿'],
  ['competence', 'n. 能力；胜任'],
  ['competition', 'n. 竞争'],
  ['compile', 'v. 汇编'],
  ['complaint', 'n. 抱怨；投诉'],
  ['complement', 'v. 补充 n. 补足物'],
  ['completion', 'n. 完成'],
  ['complexity', 'n. 复杂性'],
  ['compliance', 'n. 遵从'],
  ['compliment', 'n. 恭维 v. 称赞'],
  ['compose', 'v. 组成；创作'],
  ['compound', 'n. 化合物 adj. 复合的'],
  ['comprehend', 'v. 理解'],
  ['compress', 'v. 压缩'],
  ['compulsory', 'adj. 强制的'],
  ['compute', 'v. 计算'],
  ['conceal', 'v. 隐藏'],
  ['concede', 'v. 承认；让步'],
  ['concentration', 'n. 集中；浓度'],
  ['conception', 'n. 概念；构想'],
  ['concerning', 'prep. 关于'],
  ['concession', 'n. 让步'],
  ['concise', 'adj. 简明的'],
  ['concrete', 'adj. 具体的 n. 混凝土'],
  ['condemn', 'v. 谴责'],
  ['condense', 'v. 压缩；浓缩'],
  ['condition', 'n. 条件；状况'],
  ['confidence', 'n. 信心'],
  ['configuration', 'n. 配置；布局'],
  ['confine', 'v. 限制'],
  ['confidential', 'adj. 机密的'],
  ['configuration', 'n. 结构'],
  ['congratulate', 'v. 祝贺'],
  ['conjunction', 'n. 连接；结合'],
  ['connect', 'v. 连接'],
  ['conquer', 'v. 征服'],
  ['conscience', 'n. 良心'],
  ['conscientious', 'adj. 认真的'],
  ['consecutive', 'adj. 连续的'],
  ['consensus', 'n. 共识'],
  ['consent', 'n. 同意 v. 同意'],
  ['conservation', 'n. 保护；保存'],
  ['considerate', 'adj. 体贴的'],
  ['consideration', 'n. 考虑'],
  ['consist', 'v. 组成'],
  ['console', 'v. 安慰 n. 控制台'],
  ['consolidate', 'v. 巩固'],
  ['conspicuous', 'adj. 显眼的'],
  ['constitute', 'v. 构成'],
  ['consult', 'v. 咨询'],
  ['consultant', 'n. 顾问'],
  ['consumer', 'n. 消费者'],
  ['consumption', 'n. 消费'],
  ['contaminate', 'v. 污染'],
  ['contemplate', 'v. 沉思'],
  ['contempt', 'n. 轻视'],
  ['contend', 'v. 竞争；主张'],
  ['continual', 'adj. 不断的'],
  ['continuity', 'n. 连续性'],
  ['contradiction', 'n. 矛盾'],
  ['contrive', 'v. 设法做到；谋划'],
  ['controversial', 'adj. 有争议的'],
  ['convenience', 'n. 方便'],
  ['converge', 'v. 汇聚'],
  ['conversely', 'adv. 相反地'],
  ['convert', 'v. 转变'],
  ['convey', 'v. 传达；运送'],
  ['convict', 'v. 证明有罪 n. 囚犯'],
  ['conviction', 'n. 定罪；深信'],
  ['cooperate', 'v. 合作'],
  ['coordinate', 'v. 协调 adj. 同等的'],
  ['copyright', 'n. 版权'],
  ['corporation', 'n. 公司'],
  ['correlate', 'v. 相关'],
  ['correspondence', 'n. 通信；对应'],
  ['corrupt', 'adj. 腐败的 v. 使腐败'],
  ['cosmic', 'adj. 宇宙的'],
  ['costly', 'adj. 昂贵的'],
  ['couch', 'n. 长沙发'],
  ['counsel', 'n. 律师；忠告'],
  ['counterpart', 'n. 对应的人/物'],
  ['courtesy', 'n. 礼貌'],
  ['coward', 'n. 懦夫'],
  ['crack', 'v. 破裂 n. 裂缝'],
  ['craft', 'n. 工艺；船'],
  ['crane', 'n. 起重机；鹤'],
  ['crash', 'v. 撞毁 n. 碰撞'],
  ['crawl', 'v. 爬行'],
  ['creative', 'adj. 创造性的'],
  ['credit', 'n. 信用；学分'],
  ['creep', 'v. 爬行；蔓延'],
  ['cricket', 'n. 板球；蟋蟀'],
  ['criminal', 'n. 罪犯 adj. 犯罪的'],
  ['cripple', 'v. 使跛 n. 跛子'],
  ['crisp', 'adj. 脆的'],
  ['criterion', 'n. 标准'],
  ['critic', 'n. 批评家'],
  ['critical', 'adj. 关键的；批评的'],
  ['cruise', 'v. 巡航 n. 巡航'],
  ['crush', 'v. 压碎'],
  ['crust', 'n. 外壳；地壳'],
  ['crystal', 'n. 水晶'],
  ['cube', 'n. 立方体'],
  ['cue', 'n. 提示'],
  ['cuisine', 'n. 烹饪'],
  ['cultivate', 'v. 培养'],
  ['cumulative', 'adj. 累积的'],
  ['curb', 'v. 抑制 n. 路边'],
  ['curiosity', 'n. 好奇心'],
  ['curl', 'v. 卷曲 n. 卷发'],
  ['current', 'adj. 当前的'],
  ['curriculum', 'n. 课程'],
  ['curse', 'v. 诅咒 n. 诅咒'],
  ['curve', 'n. 曲线 v. 弯曲'],
  ['cushion', 'n. 垫子'],
  ['customary', 'adj. 习惯的'],
  ['cylinder', 'n. 圆柱'],
  ['damn', 'v. 谴责'],
  ['damp', 'adj. 潮湿的'],
  ['dash', 'v. 猛冲 n. 破折号'],
  ['database', 'n. 数据库'],
  ['dawn', 'n. 黎明 v. 破晓'],
  ['dazzle', 'v. 使目眩'],
  ['deadline', 'n. 截止日期'],
  ['deadly', 'adj. 致命的'],
  ['deaf', 'adj. 聋的'],
  ['dealer', 'n. 经销商'],
  ['dean', 'n. 院长；系主任'],
  ['decay', 'v. 腐烂 n. 衰退'],
  ['deceive', 'v. 欺骗'],
  ['decent', 'adj. 体面的'],
  ['deceptive', 'adj. 欺骗性的'],
  ['decimal', 'adj. 十进制的'],
  ['deck', 'n. 甲板'],
  ['decode', 'v. 解码'],
  ['decorate', 'v. 装饰'],
  ['decrease', 'v. 减少 n. 减少'],
  ['deduce', 'v. 推断'],
  ['deem', 'v. 认为'],
  ['deepen', 'v. 加深'],
  ['default', 'n. 违约；默认'],
  ['defect', 'n. 缺陷'],
  ['defence', 'n. 防御'],
  ['deficiency', 'n. 缺乏'],
  ['deficit', 'n. 赤字'],
  ['define', 'v. 定义'],
  ['deflect', 'v. 使偏转'],
  ['defy', 'v. 违抗'],
  ['degrade', 'v. 降级；退化'],
  ['delegate', 'n. 代表 v. 委派'],
  ['deliberately', 'adv. 故意地'],
  ['delight', 'n. 高兴 v. 使高兴'],
  ['delivery', 'n. 递送'],
  ['demand', 'v. 要求 n. 需求'],
  ['democracy', 'n. 民主'],
  ['democratic', 'adj. 民主的'],
  ['demolish', 'v. 拆除'],
  ['dense', 'adj. 稠密的'],
  ['dentist', 'n. 牙医'],
  ['deny', 'v. 否认'],
  ['departure', 'n. 离开'],
  ['dependence', 'n. 依赖'],
  ['dependent', 'adj. 依赖的'],
  ['depict', 'v. 描绘'],
  ['deposit', 'n. 存款'],
  ['depress', 'v. 使沮丧'],
  ['depression', 'n. 抑郁；萧条'],
  ['deprive', 'v. 剥夺'],
  ['deputy', 'n. 代理人；副手'],
  ['derive', 'v. 获得'],
  ['descend', 'v. 下降'],
  ['descendant', 'n. 后代'],
  ['descent', 'n. 下降；血统'],
  ['describe', 'v. 描述'],
  ['desert', 'n. 沙漠 v. 抛弃'],
  ['deserve', 'v. 应得'],
  ['design', 'v. 设计 n. 设计'],
  ['designate', 'v. 指定'],
  ['desirable', 'adj. 值得拥有的'],
  ['desire', 'n. 欲望 v. 渴望'],
  ['despair', 'n. 绝望 v. 绝望'],
  ['despatch', 'v. 派遣'],
  ['despise', 'v. 鄙视'],
  ['destination', 'n. 目的地'],
  ['destined', 'adj. 注定的'],
  ['destruction', 'n. 破坏'],
  ['destructive', 'adj. 破坏性的'],
  ['detail', 'n. 细节'],
  ['detain', 'v. 拘留'],
  ['detect', 'v. 察觉'],
  ['deteriorate', 'v. 恶化'],
  ['determination', 'n. 决心'],
  ['devastate', 'v. 摧毁'],
  ['deviate', 'v. 偏离'],
  ['device', 'n. 装置'],
  ['devise', 'v. 设计；发明'],
  ['diagnosis', 'n. 诊断'],
  ['dialect', 'n. 方言'],
  ['diameter', 'n. 直径'],
  ['dictate', 'v. 口述；命令'],
  ['dictator', 'n. 独裁者'],
  ['diet', 'n. 饮食'],
  ['differ', 'v. 不同'],
  ['differentiate', 'v. 区分'],
  ['digital', 'adj. 数字的'],
  ['dignity', 'n. 尊严'],
  ['dilemma', 'n. 困境'],
  ['diligent', 'adj. 勤奋的'],
  ['dim', 'adj. 昏暗的'],
  ['dimension', 'n. 维度'],
  ['dioxide', 'n. 二氧化物'],
  ['diplomacy', 'n. 外交'],
  ['diplomatic', 'adj. 外交的'],
  ['directly', 'adv. 直接地'],
  ['directory', 'n. 目录'],
  ['disability', 'n. 残疾'],
  ['disable', 'v. 使残废'],
  ['disadvantage', 'n. 不利'],
  ['disagree', 'v. 不同意'],
  ['disappear', 'v. 消失'],
  ['disappoint', 'v. 使失望'],
  ['disaster', 'n. 灾难'],
  ['disastrous', 'adj. 灾难性的'],
  ['discern', 'v. 辨别'],
  ['discharge', 'v. 排放；解雇'],
  ['disclose', 'v. 揭露'],
  ['discontent', 'n. 不满'],
  ['discourse', 'n. 论述'],
  ['discover', 'v. 发现'],
  ['discreet', 'adj. 谨慎的'],
  ['discrepancy', 'n. 差异'],
  ['discrete', 'adj. 分离的'],
  ['dismiss', 'v. 解雇；驳回'],
  ['disorder', 'n. 混乱'],
  ['dispatch', 'v. 派遣'],
  ['disperse', 'v. 驱散'],
  ['displace', 'v. 取代；移走'],
  ['disposal', 'n. 处理'],
  ['dispose', 'v. 处理'],
  ['disposition', 'n. 性情；倾向'],
  ['dispute', 'n. 争论 v. 争论'],
  ['disregard', 'v. 忽视'],
  ['disrupt', 'v. 扰乱'],
  ['dissolve', 'v. 溶解；解散'],
  ['distil', 'v. 蒸馏'],
  ['distinct', 'adj. 明显的'],
  ['distinction', 'n. 区别'],
  ['distort', 'v. 扭曲'],
  ['distract', 'v. 使分心'],
  ['distress', 'n. 悲痛 v. 使痛苦'],
  ['district', 'n. 地区'],
  ['disturbance', 'n. 干扰'],
  ['dive', 'v. 潜水 n. 跳水'],
  ['divert', 'v. 转移'],
  ['divide', 'v. 分开'],
  ['divine', 'adj. 神圣的'],
  ['division', 'n. 分开；部门'],
  ['divorce', 'n. 离婚 v. 离婚'],
  ['documentary', 'adj. 记录的 n. 纪录片'],
  ['domain', 'n. 领域'],
  ['domestic', 'adj. 国内的'],
  ['dominance', 'n. 支配地位'],
  ['donate', 'v. 捐赠'],
  ['doom', 'n. 厄运 v. 注定'],
  ['dose', 'n. 剂量'],
  ['dot', 'n. 圆点 v. 点缀'],
  ['drain', 'v. 排水 n. 排水管'],
  ['dramatize', 'v. 使戏剧化'],
  ['draught', 'n. 通风；草案'],
  ['drawback', 'n. 缺点'],
  ['dread', 'v. 惧怕'],
  ['dress', 'n. 连衣裙 v. 穿衣'],
  ['drift', 'v. 漂流'],
  ['drill', 'n. 钻头；训练 v. 钻孔'],
  ['drought', 'n. 干旱'],
  ['dubious', 'adj. 可疑的'],
  ['dump', 'v. 倾倒 n. 垃圾场'],
  ['duplicate', 'v. 复制 adj. 复制的'],
  ['durable', 'adj. 耐用的'],
  ['duration', 'n. 持续时间'],
  ['dusk', 'n. 黄昏'],
  ['dwell', 'v. 居住'],
  ['dye', 'n. 染料 v. 染色'],
  ['dynamic', 'adj. 有活力的'],
  ['ego', 'n. 自我'],
  ['eject', 'v. 喷射；驱逐'],
  ['elapse', 'v. 流逝'],
  ['elastic', 'adj. 有弹性的'],
  ['elderly', 'adj. 年长的'],
  ['elite', 'n. 精英'],
  ['eloquent', 'adj. 雄辩的'],
  ['embarrass', 'v. 使尴尬'],
  ['embassy', 'n. 大使馆'],
  ['embed', 'v. 嵌入'],
  ['embody', 'v. 体现'],
  ['embrace', 'v. 拥抱；包括'],
  ['emergency', 'n. 紧急情况'],
  ['emigrate', 'v. 移居国外'],
  ['eminent', 'adj. 杰出的'],
  ['emit', 'v. 发出；排放'],
  ['emotion', 'n. 情感'],
  ['emotional', 'adj. 情绪的'],
  ['emperor', 'n. 皇帝'],
  ['empire', 'n. 帝国'],
  ['empirical', 'adj. 经验主义的'],
  ['employment', 'n. 就业'],
  ['enclosure', 'n. 围场'],
  ['encode', 'v. 编码'],
  ['encounter', 'v. 遭遇'],
  ['encyclopedia', 'n. 百科全书'],
  ['endeavour', 'v. 努力'],
  ['endorse', 'v. 支持'],
  ['endow', 'v. 捐赠；赋予'],
  ['endurance', 'n. 耐力'],
  ['endure', 'v. 忍受'],
  ['energetic', 'adj. 精力充沛的'],
  ['enforce', 'v. 实施；强制执行'],
  ['engage', 'v. 从事；订婚'],
  ['engagement', 'n. 约定'],
  ['engine', 'n. 发动机'],
  ['engineering', 'n. 工程'],
  ['enlarge', 'v. 扩大'],
  ['enlighten', 'v. 启发'],
  ['enrich', 'v. 使丰富'],
  ['enrol', 'v. 注册'],
  ['ensemble', 'n. 全体'],
  ['entail', 'v. 需要；牵涉'],
  ['enterprise', 'n. 企业；事业'],
  ['entertain', 'v. 娱乐'],
  ['enthusiasm', 'n. 热情'],
  ['enthusiastic', 'adj. 热情的'],
  ['entire', 'adj. 整个的'],
  ['entrance', 'n. 入口'],
  ['entrepreneur', 'n. 企业家'],
  ['envisage', 'v. 设想'],
  ['epidemic', 'n. 流行病'],
  ['episode', 'n. 片段；一集'],
  ['equal', 'adj. 平等的 v. 等于'],
  ['equality', 'n. 平等'],
  ['equation', 'n. 方程式'],
  ['equator', 'n. 赤道'],
  ['equilibrium', 'n. 平衡'],
  ['equip', 'v. 装备'],
  ['era', 'n. 时代'],
  ['erect', 'v. 竖立 adj. 直立的'],
  ['erode', 'v. 侵蚀'],
  ['error', 'n. 错误'],
  ['erupt', 'v. 爆发'],
  ['escort', 'v. 护送 n. 护卫'],
  ['essay', 'n. 短文'],
  ['essential', 'adj. 必要的'],
  ['esteem', 'n. 尊重'],
  ['eternal', 'adj. 永恒的'],
  ['ethical', 'adj. 伦理的'],
  ['ethnic', 'adj. 种族的'],
  ['evaluate', 'v. 评估'],
  ['evaporate', 'v. 蒸发'],
  ['even', 'adj. 平坦的'],
  ['evident', 'adj. 明显的'],
  ['evil', 'n. 邪恶 adj. 邪恶的'],
  ['evoke', 'v. 唤起'],
  ['evolution', 'n. 进化'],
  ['exaggerate', 'v. 夸张'],
  ['examine', 'v. 检查'],
  ['excavate', 'v. 挖掘'],
  ['exceed', 'v. 超过'],
  ['excellence', 'n. 卓越'],
  ['excess', 'n. 过量 adj. 过量的'],
  ['excessive', 'adj. 过度的'],
  ['exclaim', 'v. 呼喊'],
  ['excursion', 'n. 远足'],
  ['execute', 'v. 执行'],
  ['executive', 'adj. 行政的 n. 主管'],
  ['exempt', 'v. 免除 adj. 被豁免的'],
  ['exert', 'v. 施加'],
  ['exhaust', 'v. 耗尽'],
  ['exile', 'v. 流放 n. 流亡'],
  ['existence', 'n. 存在'],
  ['exotic', 'adj. 异国情调的'],
  ['expectation', 'n. 期望'],
  ['expedition', 'n. 远征'],
  ['expel', 'v. 驱逐'],
  ['expend', 'v. 花费'],
  ['expense', 'n. 费用'],
  ['expert', 'n. 专家 adj. 熟练的'],
  ['expertise', 'n. 专门知识'],
  ['expire', 'v. 到期；死亡'],
  ['explode', 'v. 爆炸'],
  ['explosion', 'n. 爆炸'],
  ['explosive', 'adj. 爆炸性的'],
  ['export', 'v. 出口 n. 出口'],
  ['expose', 'v. 暴露'],
  ['exposition', 'n. 阐述；博览会'],
  ['exposure', 'n. 暴露'],
  ['exquisite', 'adj. 精致的'],
  ['extend', 'v. 延伸'],
  ['extensive', 'adj. 广泛的'],
  ['exterior', 'adj. 外部的'],
  ['externally', 'adv. 外部地'],
  ['extinguish', 'v. 熄灭'],
  ['extract', 'v. 提取 n. 摘录'],
  ['extraordinary', 'adj. 非凡的'],
  ['extravagant', 'adj. 奢侈的'],
  ['extreme', 'adj. 极端的'],
]